# The URL the site will be built for
base_url = "https://springfieldcollege-mpcs.github.io/CISC288-FinalWebsite"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# List of  menu items. Used to construct the navigation bar.
menu_items = [
    { name = "blog", url = "$BASE_URL/blog"},
    { name = "testimonial", url = "$BASE_URL/testimonials"},
    { name = "art", url = "$BASE_URL/art" },
    { name = "fake", url = "$BASE_URL/fake" },
]
